### ISSUE TITLE
Yomecolle update 2016

### ISSUE THREAD

**Issue by sadasdfdsafs** [cielavenir/yomebrowser#1]
Yomecolle updated in February and there seem to be some issues:
Error message:
"
D:\Fun\Text\yomebrowser-master>ruby yomedl.rb 644 1
Downloading...
16142
Unregistering...
yomedl.rb:56:in `+': no implicit conversion of nil into String (TypeError)
        from yomedl.rb:56:in `block (2 levels) in <main>'
        from C:/Ruby200/lib/ruby/2.0.0/net/http.rb:852:in `start'
        from yomedl.rb:46:in `block in <main>'
        from yomedl.rb:24:in `open'
        from yomedl.rb:24:in `<main>'
"

Can you please check this? Thank you for your hard work!

**Comment by cielavenir** [comment]
Bah, it looks like now api is largely changed. I have to somehow dump HTTPS packets...
